// try{
//     let x=undefined;
//     console.log(x[0]);
//     }catch{
//         console.log("Error Handling in catch");
//     }finally{
//         console.log("Finally always gets executed");
//     }
//     console.log("End");


//     try{
//         let x=undefined;
//         console.log(x[0]);
//         }catch(err){
//             console.log("Error Handling in catch",err);
//         }finally{
//             console.log("Finally always gets executed");
//         }
//         console.log("End");


try{
    console.log("hello");
    console.log(a);
    console.log("Try Ending")
}catch(err){
    console.log("Handel",err);
}finally{
    console.log("Finally")
}
console.log("End Of The Code:")

    


    